### PR TITLE
send messages directly from whatsapp

### PR DESCRIPTION
**Pull request by emanuele-em**
Let send sms directly from whatsapp, removed possibility to send sms from textbelt, whatsapp is a cleaner approach

### CODE REVIEW

**Comment by emanuele-em** [comment]
send messages from whatsapp without saving number on phone or directly from browser

**Review by MikeKlebolt — APPROVED** [review]

**Comment by MikeKlebolt** [comment]
Do you have an instance of this PR running somewhere? I'm on my mobile right now and would love to begin using this feature.

**Comment by emanuele-em** [comment]
> Do you have an instance of this PR running somewhere? I'm on my mobile right now and would love to begin using this feature.

Pull requeste was accepted, coming soon

**Comment by squad303** [comment]
We will release whatsapp version today. Thanks!

**Comment by nunogilrocha** [comment]
any news on releasing?

**Comment by emanuele-em** [comment]
> any news on releasing?

wa.1920.in

**Pull request closed without merging**
